### ISSUE TITLE
Typo p27 in the pdf, Section 3 "-d [{"item":"kale","count":20}]" should be "-d [{"item":"kale","count":10}]"

### ISSUE THREAD

**Issue by etrepum** [basho-labs/little_riak_book#12]
https://github.com/coderoshi/little_riak_book/blob/master/en/03-developers.md#creating-an-example-conflict

**Comment by etrepum** [comment]
There's a similar mistake in the command that Andy executes and the return value isn't consistent with the other return value (even the sibling says 20, when it should certainly say 10 given the previous output)

**Comment by coderoshi** [comment]
Fixed in 31f8644
