### ISSUE TITLE
Typo p34 Section 3 Link Walking "don't care the value" should be "don't care about the value"

### ISSUE THREAD

**Issue by etrepum** [basho-labs/little_riak_book#13]
https://github.com/coderoshi/little_riak_book/blob/master/en/03-developers.md#link-walking

**Comment by etrepum** [comment]
There's also a typo nearby on p35. "it's own right" should be "its own right". https://github.com/coderoshi/little_riak_book/blob/master/en/03-developers.md#what-happened-to-riak-search

**Comment by coderoshi** [comment]
Fixed in 31f8644
