### ISSUE TITLE
Typo p39 Chapter 4 operators (incorrect comma usage)

### ISSUE THREAD

**Issue by etrepum** [basho-labs/little_riak_book#14]
"But the fact that it generally hums without a hiccup, does not diminish the importance of understanding this integral part of your application stack." There really shouldn't be a comma there. It's probably better written as simply "The fact that it generally hums without a hiccup does not diminish…". If you really wanted a comma, perhaps something along the lines of "It's important to understand this integral part of your application stack, even though it generally hums along without a hiccup."

https://github.com/coderoshi/little_riak_book/blob/master/en/04-operators.md#operators

**Comment by coderoshi** [comment]
Fixed in 31f8644
