### ISSUE TITLE
p40 Chapter 4 misplaced commas

### ISSUE THREAD

**Issue by etrepum** [basho-labs/little_riak_book#15]
https://github.com/coderoshi/little_riak_book/blob/master/en/04-operators.md#how-replication-uses-the-ring

"Riak has the amazing, and probably dangerous command attach, that attaches an Erlang console to a live Riak node, loaded with all of the Riak modules."

"Riak has the amazing, and probably dangerous, command attach that attaches an Erlang console to a live Riak node loaded with all of the Riak modules."

Maybe a little clearer:

"Riak's amazing, and probably dangerous, attach command attaches an Erlang console to a live Riak node with all of the Riak modules loaded."

**Comment by coderoshi** [comment]
Fixed in 31f8644
