### ISSUE TITLE
p42 Chapter 4 run-on sentence

### ISSUE THREAD

**Issue by etrepum** [basho-labs/little_riak_book#16]
https://github.com/coderoshi/little_riak_book/blob/master/en/04-operators.md#how-replication-uses-the-ring

"Due to the structure of the Ring, how it distributes partitions, and how it handles failures, it’s relatively simple to ensure that data is replicated to as many physical nodes as possible, while being able to remain operational if a node is unavailable, by simply trying the next available node in the list."

Suggestion:

"The way that the Ring is structured allows Riak to ensure that data is always written to the appropriate number of physical nodes, even in cases where one or more physical nodes are unavailable. It does this by simply trying the next available node in the list."

Additionally, "node 10.0.1.1" should be "node A@10.0.1.1" in the previous paragraph.

Here's a suggestion for the Hinted Handoff section below:

"When a node goes down, data is replicated to a backup node. This is not a permanent solution, merely a band-aid. Riak periodically checks to ensure that the vnodes stored on each physical node should still be stored there according to the Ring. A managing process on each physical node is responsible for handing off these vnodes to the target node if it is reachable.

Hinted handoff not only helps Riak achieve high availability, it also facilitates data migration when physical nodes are added or removed from the Ring."

**Comment by coderoshi** [comment]
Fixed in 31f8644
