### ISSUE TITLE
p44 Chapter 4 riak-admin

### ISSUE THREAD

**Issue by etrepum** [basho-labs/little_riak_book#18]
https://github.com/coderoshi/little_riak_book/blob/master/en/04-operators.md#riak-admin

"Adding JavaScript or Erlang files to Riak (as we did in the developers chapter ) are not automatically found by the nodes, but they instead must be informed by either js-reload or erl-reload command."

Suggestion:

"JavaScript or Erlang files added to Riak (as we did in the developers chapter) are not usable by the nodes until they are informed about them by the js-reload or erl-reload command."

**Comment by coderoshi** [comment]
Fixed in 31f8644
