### ISSUE TITLE
p50 Chapter 4

### ISSUE THREAD

**Issue by etrepum** [basho-labs/little_riak_book#19]
https://github.com/coderoshi/little_riak_book/blob/master/en/04-operators.md#how-riak-is-built

"It’s difficult to label Riak a single project."

Suggestion:

"It’s difficult to label Riak as a single project."

https://github.com/coderoshi/little_riak_book/blob/master/en/04-operators.md#erlang

"There are a couple setting you should pay special attention to."

Suggestion:

"There are a couple of settings you should pay special attention to." or
"There are a few settings you should pay special attention to."

**Comment by coderoshi** [comment]
Fixed in 31f8644
