### ISSUE TITLE
Figure 4.1: Top overlays the beginning of the next chapter.

### ISSUE THREAD

**Issue by cnobile2012** [basho-labs/little_riak_book#20]
As I mentioned in the title Figure 4.1: Top overlays the beginning of the next chapter. This is happening in ePubs using Aldiko on my Android.

A 2nd issue is that the ePub will not display at all in the Readium plugin to Chrome. This is a significant issue as, to my knowledge, Readium is the baseline client for ePub. What happens is that it will load, but afterwards it displays nothing.

**Comment by coderoshi** [comment]
Thank, I cleaned up the top image problem.

Everything works for me in Readium. The first page is blank just like in all others (pdf, ebook), though I may remove that.
