### ISSUE TITLE
Italics problem

### ISSUE THREAD

**Issue by macintux** [basho-labs/little_riak_book#21]
Appears to be a problem with the rendering tool(s), dunno. In the paragraph below in epub (and here in GitHub, now that I preview this issue), Bitcask is surrounded by asterisks instead of italicized.

Edge case in the Markdown "spec", perhaps.

Several modern databases have swappable backends, and Riak is no different in that
respect. Riak currently supports three different storage engines---_Bitcask_,
_eLevelDB_, and _Memory_---and one hybrid called _Multi_.

**Comment by macintux** [comment]
This also rears its head in chapter 2: ACID (_Atomic_, _Consistent_...

And chapter 4: package manager (_a la_ `apt-get`

**Comment by coderoshi** [comment]
Bad form, but here's the fix 698b852dd75bd5f0447162a5caa487218bc627c1
