### ISSUE TITLE
Clarification needed

### ISSUE THREAD

**Issue by macintux** [basho-labs/little_riak_book#22]
Not sure what this paragraph means (specifically the opening clause):

Though not implemented in Pipe, Riak KV's mapreduce implementation is the
primary user of the Spidermonkey JavaScript engine---the second use is
precommit hooks.

**Comment by coderoshi** [comment]
typo. should have been "Though _now_ implemented in Pipe"

**Comment by coderoshi** [comment]
Clarified 7662d1b

**Comment by macintux** [comment]
Ok, but what does Pipe really have to do with it?

**Comment by coderoshi** [comment]
Because the javascript is configured under KV, even though it's actually a Pipe thing.

**Comment by macintux** [comment]
Not sure it adds enough value for the mental whiplash I experienced.

**Comment by coderoshi** [comment]
I think "under riak_kv, though implemented in Pipe" is descriptive enough to answer the fair question "why isn't this configured under riak_pipe".
