### ISSUE TITLE
Confusing aside

### ISSUE THREAD

**Issue by macintux** [basho-labs/little_riak_book#23]
The "Not Quite C" aside is confusing. Not sure what "concession" means, and the following sentence needs expansion/clarification.

The concession is similar to tuning A/C. To decrease read/write latency effectively improves the odds of consistency, by making requests unavailable in certain circumstances in the way a CP system would.

**Comment by coderoshi** [comment]
concession = losing privilege, which is exactly what happens. If you were able to tune to a fully CP setup by setting PR+PW > N, you would be unavailable in the case one primary went down. Your downside (concession) is the same, you just don't get C out of it... merely improving your odds of consistency.

**Comment by macintux** [comment]
To my mind, "decrease latency" means to make things faster. I assume you mean "decrease performance"?

Increasing R/W (or PR/PW) should make things slower.

Or am I still horribly confused?

**Comment by macintux** [comment]
Here's my rewrite of the paragraph:

Strictly speaking, Riak has a tunable latency/availability tradeoff, rather than consistency/availability. Making Riak run faster by keeping `r/pr/w/pw` values low will increase the likelihood of (temporarily) inconsistent results. Setting those values higher, effectively improving the odds of consistent responses, will slow down those responses and increase the likelihood that Riak will fail to respond due to a partition.

**Comment by coderoshi** [comment]
I like your rewording, I wordsmithed a bit more. Much better.

**Comment by coderoshi** [comment]
5d97459
