### ISSUE TITLE
Conflated aside

### ISSUE THREAD

**Issue by macintux** [basho-labs/little_riak_book#30]
This aside feels like it's either too short (needs more explanation) or it's two distinct thoughts that deserve separate treatment. I'm not really sure which.

<aside class="sidebar"><h3>Don't Wait Too Long</h3>

You should always keep in mind the general pattern Riak
follows when you make a change to the cluster:

_Join/Leave/Down -> Commit -> Ring state change -> Gossiped -> Hinted handoff_

Large amounts of data can take time and cause system strain to transfer, so
don't wait until it's too late to grow.
</aside>

**Comment by coderoshi** [comment]
Yeah, it made sense at the time. but the whole section grew away from the point I was apparently trying to make. Just deleted it.
