### ISSUE TITLE
Missing reference in 5th chapter

### ISSUE THREAD

**Issue by adaszko** [basho-labs/little_riak_book#45]
There seem to be a forgot reference placeholder left ("[Conflict resolution]") in the last paragraph of [Ducking conflict resolution](https://github.com/coderoshi/little_riak_book/blob/master/en/05-app-guide.md#ducking-conflict-resolution).

**Comment by adaszko** [comment]
Just noticed the same problem at the end of [Normalization](https://github.com/coderoshi/little_riak_book/blob/master/en/05-app-guide.md#normalization) section.

**Comment by adaszko** [comment]
And another one in [Large objects](https://github.com/coderoshi/little_riak_book/blob/master/en/05-app-guide.md#large-objects).

**Comment by adaszko** [comment]
And one more in [Configure at the bucket](https://github.com/coderoshi/little_riak_book/blob/master/en/05-app-guide.md#configure-at-the-bucket).

**Comment by adaszko** [comment]
Just to be specific, I'm seeing these in PDF version: https://github.com/coderoshi/little_riak_book/blob/master/rendered/riaklil-en.pdf?raw=true.

**Comment by coderoshi** [comment]
Thanks @adaszko! I'll get these fixed.
