### ISSUE TITLE
rendered PDF: curl -d single quotes getting stripped

### ISSUE THREAD

**Issue by kblake** [basho-labs/little_riak_book#6]
FYI...

Viewing the rendered PDF, the single quotes are stripped from the curl -d argument. HTML and epub renderings are fine. Attached are a couple screenshots from the PDF renderings.

![Voila_Capture5](https://f.cloud.github.com/assets/2067/17670/564ea732-4882-11e2-9281-c83edeceb173.png)
![Voila_Capture6](https://f.cloud.github.com/assets/2067/17671/584049ce-4882-11e2-83da-0edb14ffa743.png)

**Comment by coderoshi** [comment]
Wow this is an annoying little bugger. I've changed some of my formatting to avoid it, but I still don't have a satisfactory answer. Just an update to note I'm working to fix it.

**Comment by coderoshi** [comment]
A bit of hackery fixed this. Thanks so much for the close reading!

**Comment by kblake** [comment]
Thanks! :)
